version: '3.8'

services:
  react-app:
    build:
      context: .
    ports:
      - "3005:80"
    volumes:
      - ./app:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development0
  server:
      build:
        context: ./server
      ports:
        - "5005:5005"
      volumes:
        - ./server:/server
      environment:
        - DB_HOST=database
        - DB_USER=myuser
        - DB_PASSWORD=mypassword
        - DB_NAME=mydatabase

  database:
    image: mysql:8
    container_name: mysql
    ports:
      - "3307:3306" # MySQL-portti
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - db_data:/var/lib/mysql

volumes:
    db_data: